[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_01 = "ERQgbSCrDR18zuqQSUXWuKegb1DUhPqRYqe6QevGsCxR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/visheshsachdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
